### ISSUE TITLE
Contacts take forever to load when lag free Contacts loading is enabled

### ISSUE THREAD

**Issue by epicEaston197** [ResoniteModdingGroup/FlexibleContactsSort#4]
My contacts list takes much much much longer to load than usual

### Logs
[EPICEASTON197 - 2024.7.12.12 - 2024-07-12 07_24_19.log](https://github.com/user-attachments/files/16192947/EPICEASTON197.-.2024.7.12.12.-.2024-07-12.07_24_19.log)
### Video
https://github.com/user-attachments/assets/4cb58026-bb37-4827-89e9-058d55088192

**Comment by Banane9** [comment]
Did you update? That's what it looked like before I updated the mod.

**Comment by epicEaston197** [comment]
> Did you update? That's what it looked like before I updated the mod.

As far as I can tell I'm updated I've updated the mod you can even look through my log file and it Should show the version number

**Comment by epicEaston197** [comment]
> Did you update? That's what it looked like before I updated the mod.

Okay everything is up to date now and I'm not experiencing the issue
